### ISSUE TITLE
[MENU] Sous menu au hover ? 

### ISSUE THREAD

**Issue by thom4s** [TomBost-web/alx_breuil#13]
Je crois qu'il y a le sous menu des Encres au hover non ? 
Peut être le mettre au hover pour le moment simplement. On verra ensuite.

![Capture d’écran 2022-03-24 à 09 51 45](https://user-images.githubusercontent.com/1851204/159878580-bcf0b986-d74e-4463-ae66-796ed53c01eb.png)

**Comment by TomBost-web** [comment]
Pour moi ce n'était pas un hover sur le menu  après a voir, je pensais qu'il s'affichait quand on clique uniquement sur Encre.

**Comment by thom4s** [comment]
Faudra voir avec lui alors. Sur le xd, on a cette page seule. Mais je ne sais pas comment l'interpréter... 
https://xd.adobe.com/view/4f738834-42fb-48a9-9066-89fb67b97f72-1a20/screen/5aad838d-7ec5-414c-852c-5d65d081653d
(page 5)

**Comment by TomBost-web** [comment]
Oui c'est pas compréhensible, je vois pas trop non plus c'est particulier.

**Comment by thom4s** [comment]
On met de côté et on voit avec Alex.

**Comment by thom4s** [comment]
Il souhaite donc l'apparition du Menu au hover.
