### ISSUE TITLE
[ZOOM IMG]  Taille FULL + Scroll 

### ISSUE THREAD

**Issue by thom4s** [TomBost-web/alx_breuil#22]
Mettre l'image au zoom en plein format 
Pas de max-width ou max-height
Pas de overflow hidden, permettre le scroll horizontal et vertical

Permettre le drag and drop éventuellement...

**Comment by TomBost-web** [comment]
Le drag & drop, c'est le le click and drag pour se déplacer sur l'img ?

**Comment by thom4s** [comment]
Au moins le scroll vertical et horizontal en fait. Le drag and drop on verra plus tard...
